### PR TITLE
Fix fixPaddingIssues func

### PR DESCRIPTION
**Pull request by Holly-Max**
The previous version will occur bug when the input audio is longer than 1s but shorter than 1.5s.

### CODE REVIEW

**Comment by TheSeriousProgrammer** [comment]
Can you provide a code snippet to reproduce the issue which you face in the original code?

**Comment by Holly-Max** [comment]
I just use your ibm_generate to make command word "start calibration", and the problem occur when extract the features of them. Later I would upload the .wav and the print of error.

**Comment by Holly-Max** [comment]
Here is the command:  
python -m eff_word_net.generate_reference --input-dir ./wakewords/start_calibration --output-dir ./eff_word_net/sample_refs --wakeword start_calibration --model-type resnet_50_arc
Here is the error info:
error
Here is the [.wav files](https://drive.google.com/file/d/1jXASPW63DOf-QY4WHt536dt79WoVefNu/view?usp=sharing)

**Comment by TheSeriousProgrammer** [comment]
Thanks for contributing back to the community!!

**Pull request merged**
